#!/bin/bash
set -e
echo "🚀 Starte YADM-Bootstrap..."
read -rp "Installierst du ein Desktop-System (GUI)? (y/n): " use_gui
if [[ "$use_gui" == "y" || "$use_gui" == "Y" ]]; then
  echo "🖥️ Starte GUI-Setup..."
  bash ~/setup/gui##gui.sh
else
  echo "🧠 Starte Headless-Setup..."
  bash ~/setup/headless.sh
fi
