[default]
fg = "#ebdbb2"
bg = "#282828"
title = "#fabd2f"
highlight = { fg = "#282828", bg = "#fabd2f", bold = true }

[syntax]
comment = "#928374"
keyword = "#fb4934"
string = "#b8bb26"
function = "#83a598"
type = "#d3869b"

[filetype]
directory = "#458588"
symlink = "#83a598"
executable = "#b8bb26"
image = "#d3869b"
video = "#fe8019"
audio = "#b16286"
archive = "#cc241d"
document = "#83a598"
code = "#fabd2f"
other = "#928374"
